// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AcmeDomainValidationSpec defines the desired state of AcmeDomainValidation.
//
// Contains detailed information about an ACME domain validation.
type AcmeDomainValidationSpec struct {

	// The Amazon Resource Name (ARN) of the ACME endpoint.
	//
	// Regex Pattern: `^arn:aws[a-z-]*:acm:[a-z0-9-]+:[0-9]{12}:acme-endpoint/[a-zA-Z0-9-]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	AcmeEndpointARN *string                                  `json:"acmeEndpointARN,omitempty"`
	AcmeEndpointRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"acmeEndpointRef,omitempty"`
	// The domain name to validate. Use DomainScope within PrevalidationOptions
	// to control whether validation applies to the exact domain, subdomains,
	// and/or wildcards.
	//
	// The domain name to validate.
	//
	// Regex Pattern: `^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)*[a-z0-9]([a-z0-9-]*[a-z0-9])?$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	DomainName *string `json:"domainName"`
	// Configuration for domain prevalidation. Specify DnsPrevalidation with a
	// Route 53 HostedZoneId and optional DomainScope (ExactDomain, Subdomains,
	// Wildcards — each ENABLED or DISABLED).
	//
	// The prevalidation options for the domain.
	// +kubebuilder:validation:Required
	PrevalidationOptions *PrevalidationOptions `json:"prevalidationOptions"`
	// One or more tags to associate with the domain validation.
	Tags []*Tag `json:"tags,omitempty"`
}

// AcmeDomainValidationStatus defines the observed state of AcmeDomainValidation
type AcmeDomainValidationStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The time at which the domain validation was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// Details about the failure, if the validation failed.
	// +kubebuilder:validation:Optional
	FailureDetails *FailureDetails `json:"failureDetails,omitempty"`
	// Details about the prevalidation configuration.
	// +kubebuilder:validation:Optional
	PrevalidationDetails *PrevalidationDetails `json:"prevalidationDetails,omitempty"`
	// The type of prevalidation used.
	// +kubebuilder:validation:Optional
	PrevalidationType *string `json:"prevalidationType,omitempty"`
	// The status of the domain validation.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The time at which the domain validation was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// AcmeDomainValidation is the Schema for the AcmeDomainValidations API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type AcmeDomainValidation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AcmeDomainValidationSpec   `json:"spec,omitempty"`
	Status            AcmeDomainValidationStatus `json:"status,omitempty"`
}

// AcmeDomainValidationList contains a list of AcmeDomainValidation
// +kubebuilder:object:root=true
type AcmeDomainValidationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AcmeDomainValidation `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AcmeDomainValidation{}, &AcmeDomainValidationList{})
}
